### ISSUE TITLE
Broken link for the wiki for Main Variables

### ISSUE THREAD

**Issue by wdower** [ansible-lockdown/RHEL8-STIG#109]
The README's link for the Main Variables Wiki Page seems to be broken.

Trying to click that link in the README just redirects to the main wiki page, with a banner message that says "You do not have permission to update this wiki."

**Comment by uk-bolly** [comment]
hi @wdower 

Thank you for this feedback. We will hopefully be shortly migrating to a new documentation layout where we will resolve this issue and ensure that access is given.

Thanks

uk-bolly

**Comment by georgenalen** [comment]
This issue is fixed in release 2.6.0, thank you for opening the issue!

-George
