### ISSUE TITLE
Please tag a release for Benchmark Version 1 Release 7

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible-lockdown/RHEL8-STIG#111]
This is a relevant update, please tag/release it:

https://github.com/ansible-lockdown/RHEL8-STIG/pull/108

**Comment by bbaassssiiee** [comment]
@uk-bolly Please add a tag for Stig v1r7 release implemented in pull request 108

**Comment by georgenalen** [comment]
This issue is fixed in release 2.6.0, thank you for opening the issue!

-George
