### ISSUE TITLE
RHEL-08-010050 Banner on Login Screen | Missing Configuration

### ISSUE THREAD

**Issue by Rwarcards762** [ansible-lockdown/RHEL8-STIG#128]
**Describe the Issue**

In the created `01-banner-message` file in `/etc/dconf/db/local.d/`, the `banner-message-text` is configured but the enable variable is missing. This causes the banner to not show on the login screen, causing a finding.

**Expected Behavior**

Banner message shows on GUI login page.

**Actual Behavior**

Banner message does not show on GUI login page, as the enable variable is missing.

**Control(s) Affected**

RHEL-08-010050

**Possible Solution**

`01-banner-message` needs an additional line:

```ini
banner-message-enable=true
```

**Comment by uk-bolly** [comment]
hi @Rwarcards762 

Thanks again for all your work on this.

uk-bolly

**Comment by georgenalen** [comment]
This issue is fixed in release 2.6.0, thank you for opening the issue!

-George
