### ISSUE TITLE
Question regarding RHEL-08-010290 / RHEL-08-010291: Enabling FIPS mode even if not required by STIG?

### ISSUE THREAD

**Issue by Rwarcards762** [ansible-lockdown/RHEL8-STIG#130]
## Question

In `fix-cat2.yml`, RHEL-08-010290 and RHEL-08-010291 are in a block together and enable FIPS mode before applying the Fix Text.

The latest revisions of the STIG don't call for FIPS mode to be enabled for this STIG (yes, I know they are "FIPS compliant algorithms" but still.) 

Sources: See https://www.stigviewer.com/stig/red_hat_enterprise_linux_8/2022-06-15/finding/V-230251 and https://www.stigviewer.com/stig/red_hat_enterprise_linux_8/2022-06-15/finding/V-230252

**Is there a reason for this behavior in the RHEL8-STIG role? If FIPS mode isn't desired but still trying to get close to compliance, would there be a reason why this control couldn't be run without FIPS enabled? Is it not functioning as intended without FIPS enabled, and the fix text just isn't accounting for this or something?**

It seems that applying it without FIPS mode doesn't break SSH (just commenting out the block that enables FIPS mode) -- but I may just be missing something. If FIPS mode is indeed not required, then consider this an Issue regarding removing the `fips-mode-setup` statements from the `rhel_08_010290`/`rhel_08_010291` block. :)

Thanks in advance!

**Comment by uk-bolly** [comment]
hi @Rwarcards762 

Thanks again for all your work on this.

uk-bolly

**Comment by georgenalen** [comment]
This issue is fixed in release 2.6.0, thank you for opening the issue!

-George
