### ISSUE TITLE
RHEL-08-020040: TMUX Lock-Command Config | Incomplete Regex

### ISSUE THREAD

**Issue by Rwarcards762** [ansible-lockdown/RHEL8-STIG#131]
**Describe the Issue**

The regex for `RHEL-08-020040` is incomplete, causing other lines in the configuration to get overwritten (as they match the regex first) -- even if the intended line already existed in the configuration!

**Expected Behavior**

Only apply line if needed.

**Actual Behavior**

Can overwrite a completely different line in the config, and in some cases DUPLICATES the intended line.

**Control(s) Affected**

RHEL-08-020040

**Possible Solution**

See #132

**Comment by uk-bolly** [comment]
hi @Rwarcards762 

Thanks again for all your work on this.

uk-bolly

**Comment by georgenalen** [comment]
This issue is fixed in release 2.6.0, thank you for opening the issue!

-George
