### ISSUE TITLE
RHEL-08-010295: GnuTLS Encryption | Line Bug

### ISSUE THREAD

**Issue by Rwarcards762** [ansible-lockdown/RHEL8-STIG#133]
**Describe the Issue**

When applying `RHEL-08-010295`, RHEL8-STIG looks for `+VERS-ALL:` and then applies the contents of the `rhel8stig_gnutls_encryption` after it using `backrefs`. However, this causes `+VERS-ALL:` to be added again every time the STIG playbook is run.

This causes Ansible to report it as "changed" every time even when it shouldn't, as a compliant file still gets edited.

**Expected Behavior**

Only add the `+VERS-ALL:` and `rhel8stig_gnutls_encryption` if required.

**Actual Behavior**

Duplicate `+VERS-ALL` added each time, i.e. after two runs:

`+VERS-ALL:+VERS-ALL:+VERS-ALL:-VERS-DTLS0.9`...etc.

Reports changed every time, as the file is being changed.

**Control(s) Affected**

`RHEL-08-010295`

**Comment by uk-bolly** [comment]
hi @Rwarcards762 

Thanks again for all your work on this.

uk-bolly

**Comment by georgenalen** [comment]
This issue is fixed in release 2.6.0, thank you for opening the issue!

-George
