### ISSUE TITLE
RHEL-08-010740: Group Ownership by Home Dir Owner | Incorrect Ownership by "Nobody" in RHEL 8.6

### ISSUE THREAD

**Issue by Rwarcards762** [ansible-lockdown/RHEL8-STIG#134]
**Describe the Issue**

The control for RHEL-08-010740 looks at all UIDs greater than `rhel8stig_interactive_uid_start` but fails to account for `rhel8stig_interactive_uid_stop`. This causes the `nobody` user, UID 65534, to incorrectly be accounted for as an interactive user. This causes its home directory, `/`, to get its group ownership changed to `nobody`.

**Expected Behavior**

`rhel8stig_interactive_uid_stop` should be utilized for UID range.

**Actual Behavior**

`rhel8stig_interactive_uid_stop` not used, causing UID 65534 to be used in the STIG.

**Control(s) Affected**

RHEL-08-010740

**Possible Solution**

#135

**Comment by uk-bolly** [comment]
hi @Rwarcards762 

Thanks again for all your work on this.

uk-bolly

**Comment by georgenalen** [comment]
This issue is fixed in release 2.6.0, thank you for opening the issue!

-George
