### ISSUE TITLE
RHEL-08-010330 & RHEL-08-010350 | SETroubleshootD Breaks

### ISSUE THREAD

**Issue by Rwarcards762** [ansible-lockdown/RHEL8-STIG#139]
## Preface / Problem

Due to the logic for RHEL-08-010330 through RHEL-08-010350, the DBUS Daemon launch helper permissions get altered, breaking tools that call on this executable to run (such as SETroubleshootD.)

This shows up on a machine as these error logs when an SELinux permission denial occurs, such as this:

```
Activating service name='org.fedoraproject.Setroubleshootd' requested by ':1.27'
Activated service 'org.fedoraproject.Setroubleshootd' failed: The permission of the setuid helper is not correct
# Repeat like 3 more times
```

The `/usr/libexec/dbus-1/dbus-daemon-launch-helper` is altered via symlink from permissions of:

- Before: `root:dbus rwsr-x---`
- After: `root:root rwxr-xr-x`

This is due to the way the files around found and altered:

- The `find` command finds links within `/usr/lib/.build-id`
- The Ansible `file` module then follows symlinks by default, so the DESTINATION files for all of these links within `.build-id` are changed

---

## Question

Is this an intended behavior? The STIG language itself seems to say the FILES in these directories need to be altered, but symlinks (I feel) shouldn't be followed as this could lead to unexpected behavior, especially in the case of the `.build-id` files. 

The "fix" for this would just be to add `follow: no` for the `file` module call if this is unintended behavior.

Another fix could be to simply exclude the `.build-id` directory as it seems problematic:

```
find -L /lib /lib64 /usr/lib /usr/lib64 -not \( -path /lib/.build-id -prune \) -not \( -path /usr/lib/.build-id \) -perm /0022 -type f -o ! -user root -o ! -group root
```

**Comment by georgenalen** [comment]
Addressed in release 2.7.0
