### ISSUE TITLE
RHEL-08-020027/020028 | SELinux Permission Discrepancies / Faillock SELinux Denials

### ISSUE THREAD

**Issue by Rwarcards762** [ansible-lockdown/RHEL8-STIG#140]
### Describe the Issue

RHEL8-STIG, for RHEL-08-020027 and RHEL-08-020028, sets the `/var/log/faillock` (or custom faillock directory) to the `faillog_t` SELinux type.

However, the playbook then calls `restorecon -irv /var/log/faillock`, which causes all of the files within `/var/log/faillock` to be reset to the `var_log_t` type. This means that services such as SSHD lose access to these users' faillock files with this type of error:

```
setroubleshoot: SELinux is preventing /usr/sbin/sshd from 'read, write' accesses on the file /var/log/faillock/example-user.
```

However, new files that get created will inherit the `faillog_t` type... leaving old files failing but new files working.

### Expected Behavior

Custom faillock directory works as expected

### Actual Behavior

SELinux permissions are reset in a way that causes discrepancy between previously existing and new faillock files and prevents some services from using the faillock files

### Control(s) Affected

020027, 020028

### Possible Solution

Would the correct method to apply the STIG instead be to actually just change all of the files within the `/var/log/faillock` folder to the correct SELinux type via `sudo chcon --type faillog_t -Rv /var/log/faillock` -- especially because new files in that folder would inherit the parent folder's `faillog_t` type anyways -- rather than using `restorecon`?

**Comment by georgenalen** [comment]
Addressed in release 2.7.0
