### ISSUE TITLE
RHEL-08-010140 | Improvement in UX and Methodology

### ISSUE THREAD

**Issue by Rwarcards762** [ansible-lockdown/RHEL8-STIG#144]
## **Feature Request or Enhancement**
 - Feature [x]
 - Enhancement []

## **Summary of Request**

Rather than users having to provide a pre-hashed password in a variable (via `rhel8stig_bootloader_password_hash`), can instead support just providing the password as a variable. This could be done as `rhel8stig_bootloader_password` and adds to ease-of-use.

For command-line Ansible users, this allows for passing in via an Ansible Vault variable or can use something such as a prompt for the variable on launch.

For AWX / Ansible Automation Platform users, a Survey can be used as a "Password" type, so that it can be set as needed and encrypted while in use.

It may not be useful for everyone, and so it may be worth retaining the `password_hash` methodology alongside. Even if this is not accepted as a feature request, others may find it useful in their environment.

## **Describe alternatives you've considered**

I have already implemented these changes in my own local copy of RHEL8-STIG.

## **Suggested Code**

Approximate changes needed:

```diff
# README.md #####################################################
- rhel8stig_bootloader_password_hash: 'grub.pbkdf.sha512.blah'
+ rhel8stig_bootloader_password: changethispassword # Can also be made a Password Survey to hide contents

# defaults/main.yml #####################################################
# RHEL-08-010140 and RHEL-08-020280
- rhel8stig_bootloader_password_hash: 'grub.pbkdf.sha512.changethispassword'
+ rhel8stig_bootloader_password: changethispassword

# tasks/fix-cat1.yml #####################################################
"HIGH | RHEL-08-010140 | PATCH ... etc ..."
- lineinfile:
-   path: blah
-   create: true
-   etc....
### new methodology uses the included grub2-setpassword to hash the password and set it in the file for you
### only downside: currently always reports changed
+ expect:
+   command: "grub2-setpassword"
+   responses:
+     "Enter password": "{{ rhel8stig_bootloader_password }}"
+     "Confirm password": "{{ rhel8stig_bootloader_password }}"
+   timeout: 20
+ no_log: true
+ notify: confirm grub2 user cfg

# tasks/main.yml #####################################################
- replace occurrences of rhel8stig_bootloader_password_hash
+ replace with rhel8stig_bootloader_password

# templates/ansible_vars_goss.yml.j2 #####################################################
### (doesn't seem like this is used anywhere but not sure)
- rhel8stig_password_hash: {{ rhel8stig_bootloader_password_hash }}
+ rhel8stig_password: {{ rhel8stig_bootloader_password }}
```

**Comment by uk-bolly** [comment]
hi @Rwarcards762 

Thank you for the very detailed and great explanation for the proposal.

Apologies for the delay in feeding back on this one. Passwords are notoriously difficult to deal with, in many cases in these benchmarks it assumes that the accounts are local. Where as many client use third party managements tools etc.
If you have a large number of servers all utilising different passwords (as they should) then this becomes more complicated. 
We took the decision a while ago to allow users to set this up themselves however using what ever methods they wish.
Which mean the playbooks as it should run without any interactions at all.

The last line you couldn't find is a template that is used by the audit component (https://github.com/ansible-lockdown/RHEL8-STIG-Audit) which can be initiated by the role to set up and run and this is copied over and used to run the audit using the exact settings that it is being remediated with. 

Thank you once again for your feedback

kindest regards

uk-bolly
