### ISSUE TITLE
RHEL-08-010671

### ISSUE THREAD

**Issue by Squid-Bomb** [ansible-lockdown/RHEL8-STIG#145]
**Describe the Issue**
after running playbook STIG RHEL-08-010671 fails.

playbook does not modify "/usr/lib/sysctl.d/50-coredump.conf"

STIG checklist grep still returns with the following:
/usr/lib/sysctl.d/50-coredump.conf:kernel.core_pattern=|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e

**Comment by uk-bolly** [comment]
hi @Squid-Bomb 

Just following on on what George has mentioned. The control itself within STIG asks for the following
``` 
sudo grep -r kernel.core_pattern /run/sysctl.d/*.conf /usr/local/lib/sysctl.d/*.conf /usr/lib/sysctl.d/*.conf /lib/sysctl.d/*.conf /etc/sysctl.conf /etc/sysctl.d/*.conf

/etc/sysctl.d/99-sysctl.conf:kernel.core_pattern = |/bin/false
```

running sysctl -a before the playbook does show your output

```
sysctl -a | grep core_pattern
kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e
```
These settings are found in the following files
```
/usr/lib/sysctl.d/50-coredump.conf:kernel.core_pattern=|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e
/lib/sysctl.d/50-coredump.conf:kernel.core_pattern=|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e


once the remediation playbook has completed that default value is overridden by the file 99-sysctl.conf which has preference over the original settings on 50* files

```
sysctl -a | grep core_pattern
kernel.core_pattern = |/bin/false
```

I hope that helps.

Many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @Squid-Bomb 

Just a quick follow up on this issues to ensure we have covered off your request?
If you could let us know if this is as expected or if you have any other questions?

Thanks

uk-bolly
