### ISSUE TITLE
RHEL-08-010671 misses files controled by RPM

### ISSUE THREAD

**Issue by parrjd** [ansible-lockdown/RHEL8-STIG#157]
https://github.com/ansible-lockdown/RHEL8-STIG/blob/d90852a7ecf77ff3b519a05917598030e9355f48/tasks/fix-cat2.yml#L2175

Current command misses 2 different location controlled by RPM that has the setting with key=value vs key = value as the command check for.  

`grep -rs 'kernel.core_pattern\s*=\s*[?<!\|\/bin\/false]$' /run/sysctl.d/*.conf /usr/local/lib/sysctl.d/*.conf /usr/lib/sysctl.d/*.conf /lib/sysctl.d/*.conf /etc/sysctl.conf /etc/sysctl.d/*.conf /etc/sysctl.d/99-sysctl.conf| grep -d':' -f1`

The above will catch both with and without spaces to feed to the next command to remove the lines.

**Comment by parrjd** [comment]
Quick question.... Is there a reason you do not use the ini_file, and use line in file.

ini_file does a really good job handling key=value and key = value in a file, and would probably work a lot better then having to deal with the regex for matching in the replace and remove sections for sysctl, and other edits where it is key value ini style entries.

**Comment by uk-bolly** [comment]
hi @parrjd 

Happy to say that your issue #157 has been merged into devel.
also following up on the question, there is no real reason. If it is working as is and the control doesnt change we do tend to leave them. We do however address and add improvements like this when we carry out larger releases. Thank you for bringing this to out attention. We will be sure to compare and see if this can add an improvement to the content we provide.

Please let us know if you have further questions.

thanks uk-bolly

**Comment by uk-bolly** [comment]
hi @parrjd 

This has now been merged into main. I will therefore close this issue. Please feel free to open an issue if you are still seeing the issue.

many thanks

uk-bolly
