### ISSUE TITLE
Exclude mount point used by autofs for remotely mounted home directories from getent user enumeration when they are used

### ISSUE THREAD

**Issue by whitehat237** [ansible-lockdown/RHEL8-STIG#161]
Enhancement 
--------------------
**Add support for RHEL 8 systems using remote autofs mounted home directories for ldap users**
Applies when the RHEL 8 system is joined to IPA, AD, etc. and remote users do not utilize local home directories and instead use autofs maps from an IPA server via SSS lookup.

Premise
------------
The idea here is that autofs mounted home directories that reside on a remote server, such as an NFS server should be excluded from getent user enumeration because the directory does not locally reside on the RHEL 8 system, and local interactive accounts on the RHEL8 system do not use a home directory under the automount managed mount point.  I.E. "/home"

Things like ownership, bad permissions, etc should be corrected on the NFS server itself where the directories actually reside, and should not happen on every client that simply mounts the share.

Using my commit, It becomes the job of the role user to specify via defaults/main.yml that remote autofs home directories are actually in use.  The default assumption as shipped is that they are not, and no modification to the getent user enumeration command is made.  _See commit link below._

**Summary of Request**
-------------------------------------
- Add task block in prelim.yml to modify getent user enumeration shell command when remote autofs mounted home directories are being used.  (rhel8stig_autofs_remote_home_dirs is set to true)
- Add variable rhel8stig_autofs_remote_home_dirs to defaults/main.yml to declare that remote automounted home directories are being used, and set it as false by default
- Add variable rhel8stig_auto_mount_home_dirs_local_mount_point to defaults/main.yml to declare what the managed autofs mount point for home directories is, and set the default value to "/home"
- Remove local_interactive_user_dir variable and getent shell command from tasks/prelim.yml (line 123)
- Add getent user enumeration variable and getent shell command to defaults/main.yml, exactly as it was set in prelim

**Behavior of the role with these changes**
-----------------------------------------------------------------
getent user enumeration shell command is modified at run time when remote automount home directories are in use, and the managed autofs mount point is excluded.   Non local, ldap users that are looked up and authenticated via SSSD and pam, which do not have home directories residing on a local RHEL 8 machine are excluded from getent discovery.

This dramatically improves role runtime performance and prevents the role from failing with permissions errors when it can not make changes to these remote home directories.  This also prevents the automounter from automounting home directories for every user when the ldap user is not actually logged in, but was discovered via getent lookup, and automounted via an access request by a role task.

**Alternatives considered**
-----------------------------------------
I considered modifying the shell command in tasks/prelim.yml directly, per the comment, and appending another grep -v for /home.  The problems with this approach is that one cannot use tasks/prelim.yml as shipped from github, and if remote automount home directories are not being used, the location should not be excluded.

```yaml
local_interactive_user_dir_command: "getent passwd { {{ rhel8stig_int_gid }}..65535} | cut -d: -f6 | sort -u | grep -v '/var' | grep -v '/nonexistent/*' | grep -v '/run/*' | grep -v '/home/'"
```

**Suggested Code**
-------------------------------
Please see [commit](https://github.com/ansible-lockdown/RHEL8-STIG/compare/devel...whitehat237:RHEL8-STIG:devel):
https://github.com/ansible-lockdown/RHEL8-STIG/compare/devel...whitehat237:RHEL8-STIG:devel

If this looks acceptable, I'll submit a pull request.

**Comment by uk-bolly** [comment]
hi @whitehat237 

Thank you very much for the time and thorough explanation for this. I have finally had a chance to go through this and we really like the way you have done it.
If you would like to raise the PR happy to accept this in.

Many thanks again for your time and effort.

uk-bolly
