### ISSUE TITLE
RHEL-08-040001 doesn't uninstall abrt* packages

### ISSUE THREAD

**Issue by JacobBuskirk** [ansible-lockdown/RHEL8-STIG#173]
**Describe the Issue**
RHEL-08-040001 doesn't uninstall abrt* packages.

**Expected Behavior**
Any installed abrt* packages get removed

**Actual Behavior**
abrt* packages are not removed

**Control(s) Affected**
RHEL-08-040001

**Environment (please complete the following information):**
Ansible Version: 2.9.27
Host Python Version: 3.6.8
Ansible Server Python Version: 3.6.8

**Additional Notes**
https://github.com/ansible-lockdown/RHEL8-STIG/blob/devel/tasks/fix-cat2.yml#L5672
The current command does not use the -y option

**Possible Solution**
Use package module instead of shell command.

**Comment by uk-bolly** [comment]
hi @JacobBuskirk 

Thank you for you time and effort in this work. It is with feedback we are able to grow and carry on improving the content.
Some excellent catches on all the issues you have raised and thank you for taking the time with the related PRs.

Hoping to get them all sorted or feedback today.

uk-bolly

**Comment by JacobBuskirk** [comment]
Closing since this has been merged in
