### ISSUE TITLE
Ansible job started to fail approx. 2 weeks ago --STIG8 

### ISSUE THREAD

**Issue by aismahmood** [ansible-lockdown/RHEL8-STIG#190]
**Describe the Issue**

https://github.com/ansible-lockdown/RHEL8-STIG/commit/8828e3465ba70d0128ab7d0745bf4685a645062f

**Expected Behavior**
A clear and concise description of what you expected to happen. to collect the code from https://github.com/ansible-lockdown/RHEL8-STIG and execute but failing

**Actual Behavior**
A clear and concise description of what's happening.

**Control(s) Affected**
What controls are being affected by the issue

**Environment (please complete the following information):**

 - Additional Details:

**Additional Notes**
ERROR: 

ERROR! 'notify' is not a valid attribute for a Block
The error appears to be in '/runner/project/tasks/fix-cat2.yml': line 772, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: "MEDIUM | RHEL-08-010290 | PATCH | The RHEL 8 SSH daemon must be configured to use only Message Authentication Codes (MACs) employing FIPS 140-2 validated cryptographic hash algorithms. | Add MACs"
  ^ here

**Possible Solution**
Enter a suggested fix here

**Comment by aismahmood** [comment]
please provide update -

**Comment by uk-bolly** [comment]
Hi @aismahmood 

Can you please let me know what version of ansible you are running and which branch you are using?
Please not this is community based support, so we will reply when we are able.

Many thanks

uk-bolly

**Comment by aismahmood** [comment]
branches from git hub:

Default branch
[devel](https://github.com/ansible-lockdown/RHEL8-CIS)
Updated 3 weeks ago by [uk-bolly](https://github.com/uk-bolly)
Default
Active branches
[mrsteve_linting_april_2023](https://github.com/ansible-lockdown/RHEL8-CIS/tree/mrsteve_linting_april_2023)
Updated 20 hours ago by [MrSteve81](https://github.com/MrSteve81)
0
4
https://github.com/ansible-lockdown/RHEL8-CIS/pull/275  Open
[main](https://github.com/ansible-lockdown/RHEL8-CIS/tree/main)
Updated 3 weeks ago by [uk-bolly](https://github.com/uk-bolly)
0
11
Stale branches
[reports](https://github.com/ansible-lockdown/RHEL8-CIS/tree/reports)
Updated 3 years ago by [georgenalen](https://github.com/georgenalen)
735
27
[gh-pages](https://github.com/ansible-lockdown/RHEL8-CIS/tree/gh-pages)
Updated 2 years ago by [georgenalen](https://github.com/georgenalen)
547
1
[IRD-Pipeline](https://github.com/ansible-lockdown/RHEL8-CIS/tree/IRD-Pipeline)
Updated 2 years ago by [georgenalen](https://github.com/georgenalen)
405
0
[issue_139_fix](https://github.com/ansible-lockdown/RHEL8-CIS/tree/issue_139_fix)
Updated 2 years ago by [georgenalen](https://github.com/georgenalen)
405
1
https://github.com/ansible-lockdown/RHEL8-CIS/pull/140  Closed
[section_5_5_x_updates](https://github.com/ansible-lockdown/RHEL8-CIS/tree/section_5_5_x_updates)
Updated last year by [georgenalen](https://github.com/georgenalen)

**Comment by uk-bolly** [comment]
hi @aismahmood 

There has been updates in the last 3 weeks Including a new one today.
If you could pull in the latest version of the devel branch ( i assume you are using the default branch?).

Looking at your feedback it appears you are running 2.13

notify has been enabled on a block since 2.11

https://github.com/ansible/ansible/blame/stable-2.11/changelogs/CHANGELOG-v2.11.rst#L879

Is it possible you are using AAP/Tower with a runner utilising an alternate version of ansible?

Thanks

uk-bolly

**Comment by uk-bolly** [comment]
Closing issue as stale
