### ISSUE TITLE
Warn Parameter Deprecated in Ansible 2.14

### ISSUE THREAD

**Issue by JacobBuskirk** [ansible-lockdown/RHEL8-STIG#194]
**Describe the Issue**
Received the following error:
```
TASK [rhel8-stig : PRELIM | RHEL-08-010020 | Check if /boot or /boot/efi reside on separate partitions] ***
fatal: [sso-tl-pst-p12]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: _raw_params, _uses_shell, argv, chdir, creates, executable, removes, stdin, stdin_add_newline, strip_empty_ends."}
```

**Expected Behavior**
Task shouldn't fail

**Actual Behavior**
Task is failing due to warn parameter being deprecated in Ansible 2.14

**Control(s) Affected**
Any with warn parameter in shell/command

**Environment (please complete the following information):**
 - Ansible Version: 2.14.4
 - Host Python Version: 3.9.13
 - Ansible Server Python Version: 3.9.13

**Additional Notes**
https://github.com/ansible-community/ansible-build-data/blob/main/7/CHANGELOG-v7.rst#L4942

**Possible Solution**
Remove warn

**Comment by JacobBuskirk** [comment]
I plan to make a pull request with warn removed to fix this

**Comment by uk-bolly** [comment]
HI @JacobBuskirk 

Thank you again for taking the time to highlight an issue and providing the relevant fix. Your PR is now merged. I will close this issue. Please feel free to reopen if there are still issues.

thanks again

uk-bolly
