### ISSUE TITLE
FIPs mode not enabled before applying crypto changes.

### ISSUE THREAD

**Issue by prestonSeaman2** [ansible-lockdown/RHEL8-STIG#207]
**Describe the Issue**

When the crypto changes are made in RHEL-08-010290, there is no check to see if FIPS mode is enabled yet.  This causes the wrong file to be edited if FIPs is not enabled.

**Expected Behavior**
A check for if FIPs mode is enabled should be performed to ensure that the correct files are modified.

**Actual Behavior**
The check for FIPs mode seems to happen in the RHEL-08-010293 task, however, the modification of the corresponding files happens in RHEL-08-010290.  

**Control(s) Affected**
RHEL-08-010290 through RHEL-08-010293

**Possible Solution**
I believe the RHEL-08-010293 task should be performed before RHEL-08-010290.

**Comment by uk-bolly** [comment]
hi @prestonSeaman2 

Thank you for raising this query, It is with interaction we continue to enhance these baselines. I am adding this issue to the June_issues branch, that i hope to get available later today in the repository.
If all is as expected will raise the PR later this week.

many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @prestonSeaman2 

Thank you again for raising this issue. This has now been merged into main for a while, i will close this issue please open a new request if this is not resolved.

many thanks

uk-bolly
