### ISSUE TITLE
Check for and exclude users with /sbin/nologin needs to added for certain tasks before they run

### ISSUE THREAD

**Issue by prestonSeaman2** [ansible-lockdown/RHEL8-STIG#208]
**Feature Request or Enhancement**
 - Feature []
 - Enhancement [x]

**Summary of Request**
There needs to be a check and exclusion of the /sbin/nologin users from the local_interactive_user_dir_command.  As of right now users with shell= sbin/nologin are not being excluded.  Service accounts should not be treated the same.  This would improve the RHEL-08-010740, RHEL-08-010741 and RHEL-08-010750 tasks.

**Suggested Code**
A check of the item.shell=sbin/nologin needs to be performed when populating the local_interactive_user_dir_command variable for the RHEL-08-010740, RHEL-08-010741 and RHEL-08-010750 tasks.

**Comment by uk-bolly** [comment]
hi @prestonSeaman2 

Thank you for raising this query, It is with interaction we continue to enhance these baselines. I am adding this issue to the June_issues branch, that i hope to get available later today in the repository.
If all is as expected will raise the PR later this week.

many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @prestonSeaman2 

Thank you again for raising this issue. This has now been merged into main for a while, i will close this issue please open a new request if this is not resolved.

many thanks

uk-bolly
