### ISSUE TITLE
KexAlgorithms don't get replaced if abscent and files are corrupted

### ISSUE THREAD

**Issue by prestonSeaman2** [ansible-lockdown/RHEL8-STIG#209]
**Describe the Issue**
If the list returned to kex_algorythms is empty or not defined, the file is corrupted during RHEL-08-040342 task.

**Expected Behavior**
When the list of kex_algorythms is populated, an empty or undefined list should be handled so that edge cases do not corrupt the existing list.

**Actual Behavior**
When the task is run and the kex_algorythms list is returned, if the list is empty or undefined the corresponding files are corrupted.  

**Control(s) Affected**
Rhel-08-040342

**Possible Solution**
Modify RHEL-08-040432 to include case if list of kex_algorythms is absent or undefined.  Edge cases where rhel8_stig_kex == " ", or ""

**Comment by uk-bolly** [comment]
hi @prestonSeaman2 

Thank you for raising this query, It is with interaction we continue to enhance these baselines. I am adding this issue to the June_issues branch, that i hope to get available later today in the repository.
If all is as expected will raise the PR later this week.

many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @prestonSeaman2 

Thank you again for raising this issue. This has now been merged into main for a while, i will close this issue please open a new request if this is not resolved.

many thanks

uk-bolly
