### ISSUE TITLE
Enumerating over non-local mounts

### ISSUE THREAD

**Issue by prestonSeaman2** [ansible-lockdown/RHEL8-STIG#210]
**Describe the Issue**
When enumerating over file systems, non-local mounts are added to the enumeration.  There is no exclusion of non-locally mounted file systems.

**Expected Behavior**
When enumerating over file systems/mounts non-local systems should be excluded.  Other file systems on the domain should not be touched if they are not locally mounted.  

**Actual Behavior**
When enumerating over mounted file systems, the tasks currently do not exclude non-local mounts.  This causes an issue when working on domain joined systems with non-local file systems.

**Control(s) Affected**
RHEL-08-010061, RHEL-08-010196, RHEL-08-010660, RHEL-08-010710, RHEL-08-010700, RHEL-08-010780, RHEL-08-010790

**Possible Solution**
Constrain enumeration to local mounts only.  Exclude non-locally mounted file systems.

**Comment by uk-bolly** [comment]
hi @prestonSeaman2 

Thank you for raising this query, It is with interaction we continue to enhance these baselines. I am adding this issue to the June_issues branch, that i hope to get available later today in the repository.
In this case many are already only looking locally but i have spotted a couple, i am hoping the solution is enough.
If all is as expected will raise the PR later this week.

many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @prestonSeaman2 

Thank you again for raising this issue. This has now been merged into main for a while, i will close this issue please open a new request if this is not resolved.

many thanks

uk-bolly
