### ISSUE TITLE
Constrain RHEL-08-020352 to local interactive user accounts

### ISSUE THREAD

**Issue by prestonSeaman2** [ansible-lockdown/RHEL8-STIG#211]
**Describe the Issue**
The RHEL-08-020352 task is not currently constrained to only local interactive user accounts.

**Expected Behavior**
When performing RHEL-08-020352 task, only local interactive user accounts should be enumerated over.

**Actual Behavior**
The RHEL-08-020352 task enumerates over other non-local interactive user accounts.

**Control(s) Affected**
RHEL-08-020352

**Possible Solution**
Constrain enumeration to local interactive user accounts.

**Comment by uk-bolly** [comment]
hi @prestonSeaman2 

Thank you for raising this query, It is with interaction we continue to enhance these baselines. I am adding this issue to the June_issues branch, that i hope to get available later today in the repository.
If all is as expected will raise the PR later this week.

many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @prestonSeaman2 

Thank you again for raising this issue. This has now been merged into main for a while, i will close this issue please open a new request if this is not resolved.

many thanks

uk-bolly
