### ISSUE TITLE
Role not working when used with Satellite server. 

### ISSUE THREAD

**Issue by davidasexton** [ansible-lockdown/RHEL8-STIG#213]
**Describe the Issue**
When the role is runs on a host from Satellite Server it won't work. I am able to run other roles with no issue. 

**Expected Behavior**
I am able to run the role from the command line with no issues. But not from Saatellite.

**Actual Behavior**
When the role runs on a host from Satellite Server I get error `rhel8stig_firewall_service:  undefined value`.  That is with no changes to the role.

**Environment (please complete the following information):**
 - Ansible Version: [3.13.2] 
 - Host Python Version: [ Python 3.8]

**Additional Notes**
I have tried a multiple was to make the rule run from Satellite server but no luck. Any suggestions or recommendations are appreciated.

**Comment by uk-bolly** [comment]
hi @davidasexton 

Thank you for raising this query. It is with interaction we continue to enhance these baselines.
If you could please let me know which branch of the repo you are using we will be able to investigate further.
I can see the value is set in both main and devel branches, so we may require further information on how you are running it as this should be picking up the default values in assigned to the playbook.

many thanks

uk-bolly

**Comment by davidasexton** [comment]
I was using the devel branch I also tried tags 2.9.0 and 2.8.0 with no luck. I tried the role with on Satellite server 6.12 and 6.11.x with no luck.

**Comment by uk-bolly** [comment]
Hi @davidasexton 

Apologies for the delay, if you skip those associated tasks for now is that the only one that causes you an issue with satellite?
If you could possibly just run a playbook based on your settinsg with a debug for that value. It is set in the defaults/main.yml so this should work unless you have your own configurations?

many thanks

uk-bolly

**Comment by whitehat237** [comment]
@davidasexton 

You probably won't be able to run the role against satellite 6.  At least not as it's shipped.

The role installs packages via the package module, and satellite has foreman protector enabled to block package installation.  
See: https://access.redhat.com/solutions/4591281 for more information about installing packages in satellite.
I don't think that the package module is capable of dealing with foreman protector.

You could manually install every package that the role will attempt to install in advance, before running the role.  That way, those tasks "may" skip, and you might be able to get past that part.

I don't know what impact setting noexec, nodev, and nosuid in fstab on mount points for /var/lib/pulp /var/cache/pulp, /var/lib/mongodb, etc will have in regards to the functionality of pulp worker, mongodb, etc.

I think fapolicyd would have to be disabled or set to permissive mode.  The RHEL8-STIG role enables it, and I don't know if it will interfere with or block any of the satellite processes.

I also suspect that you may run into trouble with the task that restores all on disk files to the as shipped vendor provided rpm values.

I think if you were to ask redhat support, their official recommendation would be to manually apply the STIG controlls on satellite.  (What we ended up doing) Or figure out which controls you can and cannot enable, and turn them on / off accordingly in RHEL8-STIG/defaults/main.yml

I'd certainly be interested if you decide to go through this and come up with a working defaults/main.yml file for satellite.

**Comment by whitehat237** [comment]
Please disregard my previous.  I just re-read your initial comment, and realized that you aren't attempting to run the role against the satellite server, rather, from the satellite server against a different host.

**Comment by uk-bolly** [comment]
hi @davidasexton 

Thank you again for raising this issue. I will close this issue as stale. Please reopen if you are able to provide futher information.

many thanks

uk-bolly
