### ISSUE TITLE
ERROR! 'notify' is not a valid attribute for a Block

### ISSUE THREAD

**Issue by jmalpede** [ansible-lockdown/RHEL8-STIG#226]
**Describe the Issue**
After updating to main version:
9aa949c6924d49e46b11fe469469ce592bad6abf playbooks/roles/RHEL8-STIG (3.0.0-18-g9aa949c)
The playbook fails to run.

**Expected Behavior**
The Playbook should initialize and run without any errors.

**Actual Behavior**
The Playbook fails with the following error: 
amazon-ebs: ERROR! 'notify' is not a valid attribute for a Block
amazon-ebs:
amazon-ebs: The error appears to be in '/home/jmalpede/git/arfam-provision/playbooks/roles/RHEL8-STIG/tasks/fix-cat2.yml': line 826, column 3, but may                                                                                                                          
amazon-ebs: be elsewhere in the file depending on the exact syntax problem.

**Environment (please complete the following information):**
$ ansible --version
ansible 2.10.17
config file = None
python version = 3.9.16 (main, Mar 15 2023, 10:32:11) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

main - hash
9aa949c6924d49e46b11fe469469ce592bad6abf playbooks/roles/RHEL8-STIG (3.0.0-18-g9aa949c)

**Additional Notes**
If you compare the latest Main to the "working" main, you can see the differences in the ansible syntax.

**Possible Solution**
The syntax in the fix-cat2.yml file needs to be updated to resolve some ansible formatting issues.
Edit lines 839, 864, 7411 to align notify under the task name, instead of the block.
Those 3 edits resolved the issue locally in our environment.

**Comment by uk-bolly** [comment]
hi @jmalpede 

Excellent spot and thank you for raising the issue. I have raised PR #227 to pull this into devel as sson as possible.
It is interesting that we are not seeing any errors in syntax check. I will dig into this further.

many thanks

uk-bolly

**Comment by jmalpede** [comment]
I was just wondering when this change will be merged into the "Main" branch?  We like to base all our production hardening off of main.
Thanks,
John

**Comment by uk-bolly** [comment]
hi @jmalpede 

the pipeline had broken since the ansible galaxy updates only allows newer ansible versions. There was also another fix we wanted to get in prior to the next STIG release due to be released very soon.
Hope to get the next PR into devel and main next week.

Thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @jmalpede 

I believe this issue has been addressed and merged?
I will close this, but feel free to reopen if you are still experiencing this problem.

many thanks

uk-bolly
