### ISSUE TITLE
RHEL-08-010161 ansible.builtin.find module edge case bug

### ISSUE THREAD

**Issue by prestonSeaman2** [ansible-lockdown/RHEL8-STIG#242]
**Describe the Issue**
ansible.builtin.find throws error when searching for / path.  The bug is thrown when the process sub-directories are created and deleted, it seems that if the process that creates the sub-directories is finished before the ansible.builtin.find is completed it errors out.  

**Expected Behavior**
Should not error out when looking for / directory if the file that the find is looking for exists.

**Actual Behavior**
Errors out if the process has finished and the sub-directories are deleted before the find is finished.

**Control(s) Affected**
Currently affects RHEL-8-010161, but may affect any control using the ansible.builtin.find module.  

**Additional Notes**
The bug seems to be happening on line 462 in the ansible.builtin.find module.  The optional argument onerror is specified as a call to handle_walk_error(), where an instance of OSError is passed upon I/O failure. Rather than reporting the error to continue the walk of the directory tree for the supplied path (npath), handle_walk_errors() raises an exception to abort it and adds npath (“/” in this case) to the list of those skipped.  

**Possible Solution**
Use an ansible.builtin.shell:  "find..." instead of the ansible.builtin.find

**Comment by prestonSeaman2** [comment]
> **Describe the Issue** ansible.builtin.find throws error when searching for /proc/* path. The bug is thrown when the process sub-directories are created and deleted, it seems that if the process that creates the sub-directories is finished before the ansible.builtin.find is completed it errors out.
> 
> **Expected Behavior** Should not error out when looking for / directory if the file that the find is looking for exists.
> 
> **Actual Behavior** 
{"changed": false, "examined": 105374, "files": [], "matched": 0, "msg": "Not all paths examined, check warnings for details", "skipped_paths": {"/": "[Errno 22] Invalid argument: '/proc/63414/task/63414/net'"}}
Errors out if the process has finished and the sub-directories are deleted before the find is finished.
> 
> **Control(s) Affected** Currently affects RHEL-8-010161, but may affect any control using the ansible.builtin.find module.
> 
> **Additional Notes** The bug seems to be happening on line 462 in the ansible.builtin.find module. The optional argument onerror is specified as a call to handle_walk_error(), where an instance of OSError is passed upon I/O failure. Rather than reporting the error to continue the walk of the directory tree for the supplied path (npath), handle_walk_errors() raises an exception to abort it and adds npath (“/” in this case) to the list of those skipped.
> 
> **Possible Solution** Use an ansible.builtin.shell: "find..." instead of the ansible.builtin.find

**Comment by uk-bolly** [comment]
hi @prestonSeaman2 

Thank you for your patience on this issue, with so many moving parts its taken longer than we'd hope. I hopefully have now addressed this side case for the find module issue you have noted.
I have created a new branch April_24, which i am hoping to merge into devel soon. If you could possibly confirm this works as you expect?

Many thanks

uk-bolly
