### ISSUE TITLE
User session lock check and hardening bug

### ISSUE THREAD

**Issue by prestonSeaman2** [ansible-lockdown/RHEL8-STIG#245]
**Describe the Issue**
Hardening bug potentially returns unwanted lock files and binary files because of unanchored grep pattern.  After grepping for lock-enabled file there is an issue with binary files that are returned and the next task will dereference the string and give a non iterable data structure of the paths to each file concatenated together.

**Expected Behavior**
Should grep for lock-enabled file and return paths to a list variable.  After this it should loop through those list items of lock files and check if lock is enabled.

**Actual Behavior**
Greps for lock-enabled file and returns the path grepped.  Returns concatenated string of the paths returned by the grep and then looks for when the length is > 0, but some of the values concatenated have nothing to do with the desired grep.  

**Control(s) Affected**
RHEL-08-020030
RHEL-08-010310
RHEL-08-010731
RHEL-08-020022
RHEL-08-040342
RHEL-08-010295
RHEL-08-010161
RHEL-08-010660
RHEL-08-010790

**Possible Solution**
Changing the ansible.builtin.shell statement in RHEL-08-020030 task to:
ansible.builtin.shell: "grep -IlR ^lock-enabled /etc/dconf/db"

Making changes to the next task after the grep to:
path: "{{ item }}"
...
loop: "{{ rhel_08_020030_lock_enabled.stdout_lines }}"
when: rhel_08_020030_lock_enabled.stdout_lines | length > 0

**Comment by uk-bolly** [comment]
hi @prestonSeaman2 


I believe this issue has been addressed and merged?
I will close this, but feel free to reopen if you are still experiencing this problem.

many thanks

uk-bolly
