### ISSUE TITLE
RHEL-08-040110 wireless network adapter disable task has bad tag

### ISSUE THREAD

**Issue by platymatt** [ansible-lockdown/RHEL8-STIG#254]
The correct tag for this task is `V-230506` and the tag is missing the "6" as shown here below:
https://github.com/ansible-lockdown/RHEL8-STIG/blob/64313cd1252e82b2b3b52bef97f1e5f91a68dcd5/tasks/fix-cat2.yml#L6122

**Comment by platymatt** [comment]
@uk-bolly since this was merged to devel should it be closed?

**Comment by uk-bolly** [comment]
hi @platymatt 

We generally close them once they are moved to the main branch. But feel free if you are working from devel to close this.

Many thanks

uk-bolly

**Comment by platymatt** [comment]
I wasn't aware of your policy. Thanks for letting me know.
