### ISSUE TITLE
RHEL-08-020050 fails if loop list receives a single value

### ISSUE THREAD

**Issue by SeanathanVT** [ansible-lockdown/RHEL8-STIG#261]
**Describe the Issue**
Logic for RHEL-08-020050 (specifically the “Update removal-action if exists” Task) fails if a single value is passed to the loop.

**Expected Behavior**
The task, and Role, should complete execution without issue.. Regardless of the number of items sent to the Task.

**Actual Behavior**
During execution, the loop was passed a single value (/etc/dconf/db/distro.d/20-authselect). A message is received stating the following:

`Invalid data passed to ‘loop’, it requires a list, got this instead: /etc/dconf/db/distro.d/20-authselect. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup.`

**Control(s) Affected**
RHEL-08-020050

**Environment (please complete the following information):**

- branch being used: Final STIG V1R11 (released 2024-03-19)
- Ansible Version: 2.15.3
- Host Python Version: 3.11.5
- Ansible Server Python Version: 3.11.5
- Additional Details: N/A

**Additional Notes**
N/A

**Possible Solution**
As suggested in the failed task, “try adding wantlist=True to your lookup invocation or use q/query instead of lookup”.

**Comment by Phenix66** [comment]
Posted a PR with a potential more straightforward fix. Shell returns both `stdout` and `stdout_lines`, so why not just use the one that is already a list?

**Comment by SeanathanVT** [comment]
> Posted a PR with a potential more straightforward fix. Shell returns both `stdout` and `stdout_lines`, so why not just use the one that is already a list?

@Phenix66 Thanks for handling that. I was swamped yesterday but was going to look more into it today -- you beat me to it!
