### ISSUE TITLE
V-244546 Mismatched default vs stig

### ISSUE THREAD

**Issue by fallenpixel** [ansible-lockdown/RHEL8-STIG#265]
**Describe the Issue**
Reviewing the Fix text for V-244546, the fix text references a last line of `deny perm=any all : all`. This does not match the default of RHEL8-STIG. 

**Expected Behavior**
fapolicyd config should match the fix text.

**Actual Behavior**
fapolicyd rules send with `deny all all` instead.

**Control(s) Affected**
fapolicyd

**Environment (please complete the following information):**

- branch being used: [e.g. devel]
- Ansible Version: [e.g. 2.10]
- Host Python Version: [e.g. Python 3.7.6]
- Ansible Server Python Version: [e.g. Python 3.7.6]
- Additional Details:

**Additional Notes**
Anything additional goes here

**Possible Solution**
Incoming PR

**Comment by uk-bolly** [comment]
Merged to main
closing Issue

thanks

uk-bolly
