### ISSUE TITLE
Error applying playbooks referencing changes in sssd.conf

### ISSUE THREAD

**Issue by cjbidwell** [ansible-lockdown/RHEL8-STIG#29]
This check in prelim.yml is doing a find / -name sssd.conf and where this file does exist, the syntax for each file doesn't necessarily apply for that location.

i.e.:
```
cat /usr/share/logwatch/default.conf/services/sssd.conf
# You can put comments anywhere you want to.  They are effective for the
# rest of the line.

# this is in the format of <name> = <value>.  Whitespace at the beginning
# and end of the lines is removed.  Whitespace before and after the = sign
# is removed.  Everything is case *insensitive*.

# Yes = True  = On  = 1
# No  = False = Off = 0

Title = "SSSD"

# Which logfile group...
LogFile = messages

# Only give lines pertaining to the sssd service...
*OnlyService = sssd
*RemoveHeaders

# vi: shiftwidth=3 tabstop=3 et
```

and this one below isn't the sssd.conf referenced in the service.  
```
cat /usr/lib64/sssd/conf/sssd.conf
[sssd]
services = nss, pam
domains = shadowutils

[nss]

[pam]

[domain/shadowutils]
id_provider = files

auth_provider = proxy
proxy_pam_target = sssd-shadowutils

proxy_fast_alias = True
```

I'm wondering if the playbook is trying to put lines in the file where in some locations, wont work correctly.

**Comment by uk-bolly** [comment]
Hi @cjbidwell 

Thanks for raising this issue.
Will looks to address with exact path if sssd is installed.

uk-bolly

**Comment by uk-bolly** [comment]
hi @cjbidwell 

Thank you again for raising this issue. We have managed to merge #33 including this issue into devel.
Please let us know if this is not resolving your issue.

Again thank you for supporting this project
Regards

uk-bolly
