### ISSUE TITLE
rhel8stig_boot_part incorrect

### ISSUE THREAD

**Issue by mikefrompsu** [ansible-lockdown/RHEL8-STIG#298]
**Describe the Issue**
The value registered for rhel8stig_boot_part in tasks/prelim.yml is incorrect which renders the system unable to boot.

**Expected Behavior**
The UUID captured and added to the GRUB_CMDLINE_LINUX line in /etc/default/grub or skip if value is already correct

**Actual Behavior**
"boot=UUID=boot_disk" is added to GRUB_CMDLINE_LINUX line in /etc/default/grub

**Control(s) Affected**
 RHEL-08-010020 | PATCH | If /boot or /boot/efi reside on separate partitions, the kernel parameter boot=<partition> must be added to the kernel command line."

**Environment (please complete the following information):**

- branch being used: main
- Ansible Version: 2.16
- Host Python Version: Python 3.6.8
- Ansible Server Python Version: Python 3.6.8
- Additional Details: OS: Red Hat Enterprise Linux release 8.10 (Ootpa)

**Additional Notes**
line 109 in tasks/prelim.yml grabs the the third column using lsblk, but the third column is the label not the UUID of the boot partition
[root@rhel8_host~]#   lsblk -f
NAME                       FSTYPE    LABEL            UUID                      MOUNTPOINT
nvme0n1
├─nvme0n1p1
├─nvme0n1p2          vfat       UEFI_DISK       5874-.....                  /boot/efi
├─nvme0n1p3          xfs         boot_disk       842172a6-....           /boot

**Possible Solution**
Line 109 in tasks/prelim.yml
        ansible.builtin.shell: lsblk -f | grep -E "{{ rhel8stig_boot_part.stdout }}$" | awk '{ print $4 }'

**Comment by uk-bolly** [comment]
hi @mikefrompsu 

Thank you for raising this issue, working through. Investigating this further we can see why this is occuring, not all systems have a label assigned so the third field giving us the uuid.
Hoping to get a solution for this into the release for v1r14.


uk-bolly

**Comment by uk-bolly** [comment]
hi @mikefrompsu 

Thank you again for this issue. The fix has been applied and is now in the main branch and release. I will close this issue, Please reopen if you feel this is not resolved.

Many thanks

uk-bolly
