### ISSUE TITLE
Removal of conflicting ptrace settings

### ISSUE THREAD

**Issue by cpu010100** [ansible-lockdown/RHEL8-STIG#299]
The files that have conflicting settings are not registered for eventual removal.

fix-cat2.yml
      - name: "MEDIUM | RHEL-08-040282 | AUDIT | RHEL 8 must restrict usage of ptrace to descendant processes. | Find conflicting instances"
      - ansible.builtin.shell: grep -rs "kernel.yama.ptrace_scope\s*=\s*1" /run/sysctl.d/*.conf /usr/local/lib/sysctl.d/*.conf /usr/lib/sysctl.d/*.conf /lib/sysctl.d/*.conf /etc/sysctl.conf /etc/sysctl.d/*.conf | cut -d':' -f1

grep -rs "kernel.yama.ptrace_scope\s*=\s*1"
s*1 limits search to only compliant settings.
s* would search for all settings.

Adjust line to:
      - ansible.builtin.shell: grep -rs "kernel.yama.ptrace_scope\s*=\s*" /run/sysctl.d/*.conf /usr/local/lib/sysctl.d/*.conf /usr/lib/sysctl.d/*.conf /lib/sysctl.d/*.conf /etc/sysctl.conf /etc/sysctl.d/*.conf | cut -d':' -f1

**Comment by uk-bolly** [comment]
hi @cpu010100 

Thank you again for this issue. The fix has been applied and is now in the main branch and release. I will close this issue, Please reopen if you feel this is not resolved.

Many thanks

uk-bolly
