### ISSUE TITLE
Reduce unnecessary tmux sessions

### ISSUE THREAD

**Issue by dglinder** [ansible-lockdown/RHEL8-STIG#301]
In this task within the `fix-cat2.yml` playbook, specifically line 3340:

https://github.com/ansible-lockdown/RHEL8-STIG/blob/461d57261bcab3d8b3f76092b83e1449d3275da8/tasks/fix-cat2.yml#L3332-L3344

The system is configured to execute `tmux` at this line:

```
case "$name" in (sshd|login) exec tmux ;; esac
```

In situations where a person is logged, gets disconnected, and re-connects, the system executes a new `tmux` session.

This creates confusion as the user tries to reconnect to their previous sessions (if they are `tmux` savvy), or additional frustration as they (believe) they have lost their previous work (probably not true).

Changing this line to this:
```
case "$name" in (sshd|login) tmux a || exec tmux ;; esac
```
...will run `tmux a` to re-attach to the users pre-existing session if it exists, but if it doesn't then the `exec tmux` will execute the new `tmux` session as required.

This is related to https://github.com/ansible-lockdown/RHEL8-STIG/issues/232 and whenever that issue is resolved, this would be a welcome enhancement to the handling of the `tmux` sessions for any of us who are in the command line on systems with intermittent connectivity issues.

**Comment by uk-bolly** [comment]
hi @dglinder 

Thank you again for this issue. The fix has been applied and is now in the main branch and release. I will close this issue, Please reopen if you feel this is not resolved.

Many thanks

uk-bolly
