### ISSUE TITLE
Regexp does not correctly detect PermitUserEnvironment for MEDIUM | RHEL-08-010830 | PATCH |

### ISSUE THREAD

**Issue by moncapitain** [ansible-lockdown/RHEL8-STIG#314]
**Describe the Issue**
The ansible play for detecting PermitUserEnvironment in the /etc/ssh/sshd_config:
regexp: '(?i)^#?PermitUserEnvironment'
Does not appear to correctly detect the "#PermitUserEnvironment" entry.
**Expected Behavior**
The expected behavior for this ansible play would be to uncomment #PermitUserEnvironment  no to PermitUserEnvironment no.

**Actual Behavior**
Because the regexp does not appear to even find #PermitUserEnvironment it does not remove the comment.

**Control(s) Affected**
Because this ansible play does detect #PermitUserEnvironment it does not remove the comment so therefore the stig is not applied.

**Environment (please complete the following information):**

- branch being used: [main]
- Ansible Version: [core 2.16.3]
- Host Python Version: [Python 3.12.3]
- Ansible Server Python Version: [Python 3.12.3]
- Additional Details:

**Additional Notes**
Anything additional goes here

**Possible Solution**
Possible solution would be to replace the regexp entry with, have not tested this as of yet:
regexp: '^(#)?PermitUserEnvironment\b'

**Comment by moncapitain** [comment]
Please close this issue, something else is occurring in the environment that I have not yet fully researched.

**Comment by moncapitain** [comment]
This is not a bug.

**Comment by dglinder** [comment]
> This is not a bug.

Can you elaborate?  I'm opening an issue on this same task as the current REGEX doesn't correctly adjust when the line in the `sshd_config` is simply:

```
#PermitUserEnvironment no`
``

In this case the `regex:` in the `lineinfile:` module matches that line (with the leading `#`), and sees that it's already `no` and assumes it is ok.

I'm not sure what corner cases the '(?i)^#?PermitUserEnvironment' regex was trying to handle, but changing the `regex:` (remove the `#?`) appears to work as intended.

See issue #316 for my notes.

**Comment by moncapitain** [comment]
You know this is Marc Dorval right?
Yeah, something with their script is simply not applying this play, I'm
probably going to have to do my own post ansible play to apply it. I
haven't had time to research it yet.

**Comment by moncapitain** [comment]
Sorry, I thought you were someone else.
