### ISSUE TITLE
sssd.conf issues

### ISSUE THREAD

**Issue by JSurf** [ansible-lockdown/RHEL8-STIG#40]
Could have made another pull request but since you seem to rework the complete playbook anyways it seems to be better to create a bug report.

sssd.conf must have 0600 permission, otherwise the daemon does not start
See:
https://github.com/vitecde/RHEL8-STIG/commit/bb0f215f308a4888e6f986f0770b516ebd8538e1

Another thing we are not sure how to handle.
Currently the playbook checks if sssd.conf exists in a pre task and skips several of the tasks if the file does not exist, but the sssd rpm does not provide a sssd.conf file, so the tasks are skipped when running the playbook on a fresh installed system. We currently workaround the issue by creating an empty sssd.conf. Wondering if the check for existence makes sense or if this playbook should just create the file when it does not exist

**Comment by uk-bolly** [comment]
hi @JSurf 

Thank you for the continued feedback, assisting in continually improving this role.
As you have noted we are in the process of doing an update to a later baseline and about to release a new part of the role, so there are a number of changes currently taking place.
We will look to update the permissions control and work through on the improvement for the sssd.conf file existence.

We hope to have this resolved by the end of the day into devel.

Thanks
uk-bolly

**Comment by georgenalen** [comment]
This issue was resolved in the 2.2.0 release
