### ISSUE TITLE
RHEL8 Benchmark STIG released

### ISSUE THREAD

**Issue by kz6fittycent** [ansible-lockdown/RHEL8-STIG#5]
Greetings, 

Firstly, I wanted to thank you for the hard work committed to this project and the results that come from it. I noticed that the role for RHEL8-STIG is still based on the draft and wondered if work was already under way for the[ latest release](https://public.cyber.mil/announcement/stig-update-disa-has-released-the-red-hat-enterprise-linux-8-stig/) for the benchmark STIG?

Thanks in advance.

**Comment by georgenalen** [comment]
Hello,
 Thanks for the support, it's great to hear it. You are correct RHEL8STIG came out of draft last week and have been in the process of getting those changes into the role. There were some significant changes between draft and release so it's taking a bit more time than expected, I thought it only be a couple days. The unofficial ETA for our release will be by mid week next week. 
Thanks again
