### ISSUE TITLE
RHEL-08-010421 Same grubby behavior than on other tasks

### ISSUE THREAD

**Issue by JSurf** [ansible-lockdown/RHEL8-STIG#58]
**Describe the Issue**
RHEL-08-010421 always executes grubby without checking if page_poison=1 is already set

**Expected Behavior**
RHEL-08-010421 should check if page_poison=1 is already set
Task should implement similar 'when' conditions as for example RHEL-08-010422 and others before running grubby

**Actual Behavior**
RHEL-08-010421 does not check if page_poison=1 is already set and always runs grubby which may cause for example unexpected config changes to /etc/default/grub (moving page_poison to the end of the line)

**Control(s) Affected**
RHEL-08-010421

**Environment (please complete the following information):**
does not matter

**Additional Notes**
Maybe there is a reason unknown to me, this is the only rule with grubby that does not do a check ?

**Possible Solution**
https://github.com/vitecde/RHEL8-STIG/commit/cfe8e3d99e243d1a89a94b7810ca43fe08d6bba8
If you prefer a pull request please let me know

**Comment by georgenalen** [comment]
Addressed in release 2.3.0
