### ISSUE TITLE
RHEL-08-020024 is not using the rhel8stig_maxlogins variable

### ISSUE THREAD

**Issue by rheak** [ansible-lockdown/RHEL8-STIG#64]
**Describe the Issue**
The task `RHEL-08-020024` does not use the variable `rhel8stig_maxlogins` it is currently using a hard coded value of '10'.

**Expected Behavior**
The task to use the variable to define the value for max logins.

**Actual Behavior**
The task does not use the variable since the value is hard coded.

**Control(s) Affected**
https://www.stigviewer.com/stig/red_hat_enterprise_linux_8/2021-06-14/finding/V-230346

**Environment (please complete the following information):**
- RHEL 8

**Additional Notes**

**Possible Solution**

**Comment by uk-bolly** [comment]
Hi @rheak 

Thank you for taking the time to highlight this bug, we are currently looking to update to the latest release and will be sure to add this fix into that release.

Regards

uk-bolly

**Comment by uk-bolly** [comment]
hi @rheak 

Thank you again for taking the time to raise this issue, this should now be resolved in the latest devel branch this also includes updates to the latest STIG release.

I will close this call over the next week unless you have any further feedback?

Many thanks again

uk-bolly
