### ISSUE TITLE
RHEL-08-010201 task is replacing ClientAliveInterval value with ClientaliveCountMax.

### ISSUE THREAD

**Issue by rheak** [ansible-lockdown/RHEL8-STIG#65]
**Describe the Issue**
RHEL-08-010201 task is replacing ClientAliveInterval value with ClientaliveCountMax, which eliminates the ClientAliveInterval value in the /etc/ssh/sshd_config file.

**Expected Behavior**
RHEL-08-010201 task should find the ClientAliveInterval line in /etc/ssh/sshd_config and update the configured value with the variable `rhel8stig_ssh_session_timeout`

**Actual Behavior**
The ClientAliveInterval line in /etc/ssh/sshd_config is being replaced by ClientAliveCountMax 0.

**Control(s) Affected**
[What controls are being affected by the issue](https://www.stigviewer.com/stig/red_hat_enterprise_linux_8/2021-06-14/finding/V-244525)

**Environment (please complete the following information):**

**Additional Notes**

**Possible Solution**
`
- name: "MEDIUM | RHEL-08-010201 | PATCH | The RHEL 8 SSH daemon must be configured with a timeout interval"
  lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '(?i)^#?ClientAliveInterval.*'
      line: "ClientAliveInterval {{ rhel8stig_ssh_session_timeout }}"
  notify: restart sshd
  when:
      - rhel_08_010201
      - rhel8stig_ssh_required
  tags:
      - RHEL-08-010201
      - CAT2
      - CCI-001133
      - SRG-OS-000163-GPOS-00072
      - SV-244525r743824_rule
      - V-244525
      - ssh
`

**Comment by uk-bolly** [comment]
hi @rheak 

Thank you for taking the time to raise this bug and explaining the issue. We are currently working through the next STIG release and will be adding this as part of the next update.

regards

uk-bolly

**Comment by uk-bolly** [comment]
hi @rheak 

Thanks again for the feedback, this should be resolved in the latest devel branch incorporating the latest stig release updates as well.
I will close this issue over the next week unless you have any questions?

Many thanks

uk-bolly
