### ISSUE TITLE
modprobe modifications for 

### ISSUE THREAD

**Issue by jmalpede** [ansible-lockdown/RHEL8-STIG#70]
**Describe the Issue**
Scap scans report the modeprobe modifications as non compliant.
SRG-OS-000095-GPOS-00049 - RHEL 8 must disable the asynchronous transfer mode (ATM) protocol. - Fail
SRG-OS-000095-GPOS-00049 - RHEL 8 must disable the controller area network (CAN) protocol. - Fail
SRG-OS-000095-GPOS-00049 - RHEL 8 must disable the stream control transmission protocol (SCTP). - Fail
SRG-OS-000095-GPOS-00049 - RHEL 8 must disable the transparent inter-process communication (TIPC) protocol. - Fail

The issue is that the RHEL-08-040021, RHEL-08-040022, RHEL-08-040023 and RHEL-08-040024 controls in the RHEL8-STIG add uppercase entries into the blacklist.conf. (Note: It is strange that it is listed in upper case in the DOD Stig Viewer resolution instructions.)  

**Expected Behavior**
Modprobe entries should be added in lower case. (I have never seen uppercase module names in linux.

**Actual Behavior**
Modprobe blacklist entries are beein added in uppercase, thus the check fails when running our scap scans.

**Control(s) Affected**
RHEL-08-040021, RHEL-08-040022, RHEL-08-040023 and RHEL-08-040024

**Environment (please complete the following information):**
ansible              2.10.7
ansible-base         2.10.12
ansible-lint         5.1.3

**Possible Solution**
change the modeprob.d blackist modifications from upper to lowercase.  (I manually made the change and now the scap scans pass those checks.)

**Comment by uk-bolly** [comment]
Hi @jmalpede 

Thank you for taking the time in raising this issue. Feedback is helpful and the way in which we can all improve the content. 
I believe this has recently been added to the devel branch, which is due to be pushed to main over the next week dependent if any major issues occur.
Please let us know if that does  solve the issue or if you are still seeing problems?

Many thanks again

uk-bolly

**Comment by jmalpede** [comment]
Thanks for the update.
Keep up the good work.
-John
