### ISSUE TITLE
rocky linux support

### ISSUE THREAD

**Issue by jmalpede** [ansible-lockdown/RHEL8-STIG#82]
Now that Centos has removed the repos for centos 8 (mirror.centos.org) and only the stream versions are available.  Are there any plans for rocky Linux support?  We prefer to run centos in our dev and uat environments and like to keep are versions in-line with RHEL.  If we go to Streams, this is not possible, because Streams is more of an Alpha version than following the RHEL like CentOS did.

**Comment by uk-bolly** [comment]
hi @jmalpede 

Thank you for taking the time to raise the issue.
I am happy to say that we do test the benchmark on both Rocky and AlmaLinux, these work as expected. Noting that any crypto controls can still cause issues with updates.
The benchmark itself is specifically for RHEL but is does work on other platforms. We are also extending it to run against base container images.
I will be sure to make it clear that this is tested on the alternatives within the README
This should be added in the next release hopefully out this week with the new benchmark updates.

uk-bolly

**Comment by jmalpede** [comment]
Thanks for the update.

We use the RHEL8-STIG as a sub-module in our build process.  We are running
a older build and it doesn't apply the changes to rocky linux.
I will update to the latest build to see if that works.
Is there anything else I should be aware of for rocky support?

We really appreciated your work on these projects.  It makes our life so
much easier when it comes to hardening systems.

Thanks,

John

**Comment by uk-bolly** [comment]
hi @jmalpede 

Sorry for the delay, the changes as you've probably seen are in devel. There are a number of changes including pipeline testing that have been holding us back from releasing sooner.
We are working on the rhel7 today and hoping to get the this out by the end of this week.

regards

uk-bolly

**Comment by uk-bolly** [comment]
hi @jmalpede 

This is now in devel and rocky is actually used for our pipeline testing.
We should be merging to main this week.

Happy this is working as expected and will close.

Please let us know if this is not as expected.

Many thanks

ukbolly

**Comment by jmalpede** [comment]
Hi ukbolly.  just checking to see if a merge is coming anytime soon.  

I appreciate all your hard work.
thanks.
John
