### ISSUE TITLE
Error with RHEL-08-040137 - Failed

### ISSUE THREAD

**Issue by ccravens** [ansible-lockdown/RHEL8-STIG#93]
RHEL-08-040137 - The RHEL 8 fapolicy module must be configured to employ a deny-all, permit-by-exception policy to allow the execution of authorized software programs

**Describe the Issue**
When running RHEL-8 STIG, error occurs on step RHEL-08-040137:

```
TASK [/RHEL8-STIG : MEDIUM | RHEL-08-040137 | PATCH | The RHEL 8 fapolicy module must be configured to employ a deny-all, permit-by-exception policy to allow the execution of authorized software programs. | Set fapolicy whitelist] ***
failed: [] (item=allow exe=/usr/libexec/platform-python : ftype=text/x-python) => {"ansible_loop_var": "item", "changed": false, "item": "allow exe=/usr/libexec/platform-python : ftype=text/x-python", "msg": "Destination /etc/fapolicyd/fapolicyd.rules does not exist !", "rc": 257}
failed: [] (item=allow exe=/usr/libexec/platform-python : ftype=text/x-python) => {"ansible_loop_var": "item", "changed": false, "item": "allow exe=/usr/libexec/platform-python : ftype=text/x-python", "msg": "Destination /etc/fapolicyd/fapolicyd.rules does not exist !", "rc": 257}
failed: [] (item=deny_audit perm=any pattern=ld_so : all) => {"ansible_loop_var": "item", "changed": false, "item": "deny_audit perm=any pattern=ld_so : all", "msg": "Destination /etc/fapolicyd/fapolicyd.rules does not exist !", "rc": 257}
failed: [] (item=allow exe=/usr/libexec/platform-python : ftype=text/x-python) => {"ansible_loop_var": "item", "changed": false, "item": "allow exe=/usr/libexec/platform-python : ftype=text/x-python", "msg": "Destination /etc/fapolicyd/fapolicyd.rules does not exist !", "rc": 257}
failed: [] (item=deny_audit perm=any pattern=ld_so : all) => {"ansible_loop_var": "item", "changed": false, "item": "deny_audit perm=any pattern=ld_so : all", "msg": "Destination /etc/fapolicyd/fapolicyd.rules does not exist !", "rc": 257}
failed: [] (item=deny all all) => {"ansible_loop_var": "item", "changed": false, "item": "deny all all", "msg": "Destination /etc/fapolicyd/fapolicyd.rules does not exist !", "rc": 257}
failed: [] (item=deny_audit perm=any pattern=ld_so : all) => {"ansible_loop_var": "item", "changed": false, "item": "deny_audit perm=any pattern=ld_so : all", "msg": "Destination /etc/fapolicyd/fapolicyd.rules does not exist !", "rc": 257}
failed: [] (item=deny all all) => {"ansible_loop_var": "item", "changed": false, "item": "deny all all", "msg": "Destination /etc/fapolicyd/fapolicyd.rules does not exist !", "rc": 257}
failed: [] (item=deny all all) => {"ansible_loop_var": "item", "changed": false, "item": "deny all all", "msg": "Destination /etc/fapolicyd/fapolicyd.rules does not exist !", "rc": 257}
```

When looking at the `/etc/fapolicyd` directory, I see this:

```
[root@ip-192-168-0-10 ~]# ls /etc/fapolicyd/
compiled.rules  fapolicyd.conf  fapolicyd.trust  rules.d  trust.d
```

It looks like `fapolicyd.rules` no longer exists?

**Expected Behavior**
No error when running RHEL8-STIG

**Actual Behavior**
Error message displayed above

**Control(s) Affected**
`RHEL-08-040137`

**Environment (please complete the following information):**
```
$ ansible --version
ansible [core 2.12.2]
  config file = ansible.cfg
  configured module search path = ['/Users/ccravens/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/ccravens/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.7 (default, Sep  3 2021, 12:37:55) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 3.0.1
  libyaml = True
```

**Additional Notes**
Anything additional goes here

**Possible Solution**
It looks like the scripts may need to be updated to use the `rules.d/` folder:
```
[root@ip-192-168-0-10 ~]# ls /etc/fapolicyd/rules.d/
10-languages.rules  30-dracut.rules    40-bad-elf.rules     42-trusted-elf.rules   72-shell.rules         95-allow-open.rules
20-patterns.rules   30-updaters.rules  41-shared-obj.rules  70-trusted-lang.rules  90-deny-execute.rules
```

**Comment by ccravens** [comment]
Installation of `fapolicy` a few weeks ago created this directory structure:

```
[root@ip-192-168-0-10 ~]# ls /etc/fapolicyd/
fapolicyd.conf  fapolicyd.rules  fapolicyd.trust  trust.d
```

New directory structure is this:
```
[root@ip-192-168-0-10 ~]# ls /etc/fapolicyd/
compiled.rules  fapolicyd.conf  fapolicyd.trust  rules.d  trust.d
```

Going to work a fix and submit PR

**Comment by ccravens** [comment]
Please refer to: https://github.com/linux-application-whitelisting/fapolicyd#rule-ordering

And: https://github.com/linux-application-whitelisting/fapolicyd/blob/main/rules.d/README-rules

**Comment by uk-bolly** [comment]
hi @ccravens 

Thank you for taking the time to provide the feedback on this issue.
I am trying to replicate the problem, 
based on clean install of rocky8 or rhel8 with the latest vendor provided fapolicyd rpm installed
fapolicyd-1.0.2-6.el8.x86_64 

this appears to create both files at installation
[root@rocky8-bios fapolicyd]# dnf whatprovides /etc/fapolicyd/fapolicyd.rules | grep fapolicyd-1.0.2-6.el8.x86_64
fapolicyd-1.0.2-6.el8.x86_64 : Application Whitelisting Daemon

[root@rocky8-bios fapolicyd]# dnf whatprovides /etc/fapolicyd/fapolicyd.conf | grep fapolicyd-1.0.2-6.el8.x86_64
fapolicyd-1.0.2-6.el8.x86_64 : Application Whitelisting Daemon

[root@rhel8-efi fapolicyd]# dnf whatprovides /etc/fapolicyd/fapolicyd.rules | grep fapolicyd-1.0.2-6.el8.x86_64
fapolicyd-1.0.2-6.el8.x86_64 : Application Whitelisting Daemon

[root@rhel8-efi fapolicyd]# dnf whatprovides /etc/fapolicyd/fapolicyd.conf | grep fapolicyd-1.0.2-6.el8.x86_64
fapolicyd-1.0.2-6.el8.x86_64 : Application Whitelisting Daemon


The rpm info shows that the package was built last year.
Name        : fapolicyd
Version     : 1.0.2
Release     : 6.el8
Architecture: x86_64
Install Date: Tue 08 Mar 2022 10:18:55 GMT
Group       : Unspecified
Size        : 268498
License     : GPLv3+
Signature   : RSA/SHA256, Fri 26 Mar 2021 08:10:43 GMT, Key ID 199e2f91fd431d51
Source RPM  : fapolicyd-1.0.2-6.el8.src.rpm
Build Date  : Thu 25 Mar 2021 15:14:48 GMT

If you could please let me know further information around your setup I will continue to try and replicate this. 
Reading the information from the link provided this is not currently in the default packages from the vendor on a basic install, if this a pre release that is coming to rhel8 that you are using?

Many thanks

uk-bolly

**Comment by ccravens** [comment]
Hello @uk-bolly! Thanks for looking into this. It looks like an issue due to a newer release on CentOS8 Stream. These are my configurations:

OS:
```
[root@ip-192-168-0-10 ~]# cat /etc/redhat-release 
CentOS Stream release 8
```

FA Policy Daemon:
```
[root@ip-192-168-0-10 ~]# dnf whatprovides /etc/fapolicyd/compiled.rules
Last metadata expiration check: 0:29:59 ago on Tue 08 Mar 2022 08:24:46 AM EST.
fapolicyd-1.1-1.el8.x86_64 : Application Whitelisting Daemon
Repo        : @System
Matched from:
Filename    : /etc/fapolicyd/compiled.rules

fapolicyd-1.1-1.el8.x86_64 : Application Whitelisting Daemon
Repo        : appstream
Matched from:
Filename    : /etc/fapolicyd/compiled.rules
```

```
[root@ip-192-168-0-10 ~]# rpm -qi fapolicyd
Name        : fapolicyd
Version     : 1.1
Release     : 1.el8
Architecture: x86_64
Install Date: Mon 07 Mar 2022 11:58:05 PM EST
Group       : Unspecified
Size        : 301485
License     : GPLv3+
Signature   : RSA/SHA256, Mon 28 Feb 2022 09:51:48 AM EST, Key ID 05b555b38483c65d
Source RPM  : fapolicyd-1.1-1.el8.src.rpm
Build Date  : Sat 26 Feb 2022 08:07:20 PM EST
Build Host  : x86-01.mbox.centos.org
Relocations : (not relocatable)
Packager    : CentOS Buildsys <bugs@centos.org>
Vendor      : CentOS
URL         : http://people.redhat.com/sgrubb/fapolicyd
Summary     : Application Whitelisting Daemon
Description :
Fapolicyd (File Access Policy Daemon) implements application whitelisting
to decide file access rights. Applications that are known via a reputation
source are allowed access while unknown applications are not. The daemon
makes use of the kernel's fanotify interface to determine file access rights.
```

This is a breaking issue for me, so I'm going to submit a WIP PR to collaborate on a fix on here with you.

Thanks!

**Comment by ccravens** [comment]
@uk-bolly I'm going to be working to collaborate a fix in this WIP PR: https://github.com/ansible-lockdown/RHEL8-STIG/pull/94

**Comment by ccravens** [comment]
@uk-bolly working a fix in this PR: https://github.com/ansible-lockdown/RHEL8-STIG/pull/95

Happy to collaborate and code reviews to make sure the fix is good with the Mindpoint team and follows the standards put in place with the project.

**Comment by uk-bolly** [comment]
Hi @ccravens

Unfortunately we are no longer supporting CentOS since it moved to stream, This is purely due to the changes that take place in a stream release along with having consistency within a release. The overhead to maintain this that change at this rate could require extremely regular changes.
We have been testing and call out that we do however test and support running on either of the two alternatives Rocky linux or Almalinux.
Happy to have a stream branch if the wider community wished to adopt it?
It is also noted that this is not clear enough or easily seen in the latest release that the support has been removed so we will update the README to make this clearer

Thanks 
uk-bolly

**Comment by ccravens** [comment]
@uk-bolly I'd be happy to support a CentOS 8 Stream release branch if we'd like to see how difficult it would be to maintain and support such a branch (or I can just maintain a separate fork of the project). We run RHEL8-STIG frequently and I feel that CentOS 8 Stream will be an important distro to support for many in the community.

From what I understand CentOS 8 Stream will serve as the upstream of RHEL 8. Maybe I'm missing something but I don't imagine RHEL 8 and CentOS 8 Stream to diverge much? Thanks!

**Comment by uk-bolly** [comment]
hi @ccravens 

I believe this has now been pulled into rhel8 and the changes have been make accordingly. Did you still want to look at a centos8 branch that can be the precursor rhel8 before the STIG baseline is updated?

Thanks

uk-bolly

**Comment by ccravens** [comment]
Hello @uk-bolly that's a good question, and yes I agree a `centos8-stream` precursor branch may be necessary.

From my understanding, CentOS 8 Stream is designed to now be the immediate upstream for RHEL 8 (Fedora -> CentOS 8 Stream -> RHEL).

Because CentOS 8 Stream is considered "latest and greatest cutting edge", there may be instances where the CentOS 8 Stream updates may not be compatible with current RHEL 8, and the Ansible scripts won't work. My initial thoughts is that we may want to have a centos8-stream branch that is able to stay up-to-date with support for the latest CentOS 8 Stream. But those changes will eventually need to make it into RHEL 8 as well at some point in the future since RHEL 8 will be updated with those changes as well.

A good example of this is with an fapolicyd update I submitted a few months back due to a change in how fapolicyd manages rules in newer versions. CentOS 8 Stream incorporated this newer fapolicyd while I assume RHEL 8 probaby did (does) not.

Please let me know your thoughts, thanks!

**Comment by bbaassssiiee** [comment]
The directory structure of fapolicyd changed since rhel 8.4

**Comment by uk-bolly** [comment]
hi @ccravens 

I believe this is now resolved and covered off in the later releases for the rhel repo?
Still happy to have a separate branch for Centos if you wish? Although we have seen many of our own customers already move away to one of the alternatives mentioned.

Many thanks as always

uk-bolly
