### ISSUE TITLE
CentOS Support Removed - Why?

### ISSUE THREAD

**Issue by ccravens** [ansible-lockdown/RHEL8-STIG#96]
**Describe the Issue**
Recently support for CentOS was explicitly removed. Been running these scripts against our CentOS 8 Stream OS for months without issue, why has this been enforced like this?

https://github.com/ansible-lockdown/RHEL8-STIG/commit/aa8714a375e79deeea3985a4e8d269c56b985ac7

**Expected Behavior**
I would like to use these scripts against our CentOS 8 Stream OS

**Actual Behavior**
I get an error when running latest scripts against our CentOS 8 Stream OS: 

```
TASK [RHEL8-STIG : Check OS version and family] ****************************************************************************************************
fatal: [example.com]: FAILED! => {
    "assertion": "(ansible_distribution != 'CentOS' and ansible_os_family == 'RedHat' or ansible_os_family == \"Rocky\") and ansible_distribution_major_version is version_compare('8', '==')",
    "changed": false,
    "evaluated_to": false,
    "msg": "This role can only be run against RHEL/Rocky 8. CentOS 8 is not supported."
}
```

**Control(s) Affected**
All

**Environment (please complete the following information):**
N/A

**Additional Notes**
Anything additional goes here

**Possible Solution**
It would be important to not exclude CentOS 8 Stream support as it is the upstream for RHEL 8 and can help identify issues that may come up in RHEL 8.

**Comment by uk-bolly** [comment]
hi @ccravens 

Apologies for not making this clearer sooner. I have raised a PR to enable it to be run it on your CentOS system. Thank you very much for your offer to work with us for the stream supported release.
I am not sure if you are on discord and able to join the new discord channels we have created maybe this could be a great talking point on how we can get this supported with more input.

Many thanks once again for raising and highlighting the lack of clarity on the documentation. It is only through feedback we can make this better.

best regards

uk-bolly

**Comment by ccravens** [comment]
No worries! Yes I'll join discord I'm happy to support this project is amazing and want to give back where I can.

But when I ran the updates and saw that had been added it really confused me :)

Thanks! See you on discord!

**Comment by ccravens** [comment]
@uk-bolly Do we need to be invited to the Discord server? If so my email is `chad.cravens@ossys.com`

Thanks!

<img width="458" alt="image" src="https://user-images.githubusercontent.com/1319049/157301168-0baa92f1-3029-410b-954d-1459c12c4319.png">

**Comment by georgenalen** [comment]
@ccravens,
 Thanks for being understanding on the CentOS Stream support. It wasn't an easy decision but that was the decision that was made. 

 For Discord, if you're using the invite from the readme it should work, it was created as a never expire invite and it's still active (from what I can see in the settings). As a backup I was going to create another one off invite to send your way but it looks like discord is having issues right now, I can't create invites the status page is showing a bunch of problems. I'll. keep checking the status page to see if the issues clear up and let you know. Let us know if you get into Discord, if not I'll keep this open and get an invite your way here. 

-George

**Comment by ccravens** [comment]
Hello @georgenalen I was finally able to join the discord :)

I guess I don't understand yet the reason for removing support for CentOS. This is something I'll reach out to discord and we can take the conversation there, thanks!
